spring:
  datasource:
    url: jdbc:mysql://localhost:3306/casa_do_codigo?createDatabaseIfNotExist=true
    username:  root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update